# Generated by Django 4.1.5 on 2023-04-03 19:23

import core.product.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="order",
            field=core.product.fields.OrderField(blank=True, null=True),
        ),
    ]
