# Generated by Django 4.1.5 on 2023-04-11 18:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_productimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
    ]
